---
all:
  hosts:
    localhost:
      ansible_connection: local
      ansible_python_interpreter: "{{ ansible_playbook_python }}"
  children:
    talos_controlplane:
      hosts:
        talos-control-01:
          ansible_host: 172.16.31.11
        talos-control-02:
          ansible_host: 172.16.31.12
        talos-control-03:
          ansible_host: 172.16.31.13
    talos_worker:
      hosts:
        talos-worker-01:
          ansible_host: 172.16.31.21
        talos-worker-02:
          ansible_host: 172.16.31.22
        talos-worker-03:
          ansible_host: 172.16.31.23
  vars:
    machine:
      memory: 2560
      vcpu: 2
      disk: 10737418240
