---
dependency:
  name: galaxy
  options:
    ignore-certs: false
    ignore-errors: false
    role-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml
    requirements-file: ${MOLECULE_PROJECT_DIRECTORY}/requirements.yml

ansible:
  cfg:
    defaults:
      host_key_checking: false
      verbosity: 1
    ssh_connection:
      pipelining: true
  env:
    ANSIBLE_FORCE_COLOR: "1"
    ANSIBLE_LOAD_CALLBACK_PLUGINS: "1"

  executor:
    backend: ansible-playbook
    args:
      ansible_playbook:
        - --force-handlers
        - --inventory=${MOLECULE_PROJECT_DIRECTORY}/extensions/molecule/default/inventory/
      ansible_navigator:
        - --mode stdout
        - --pull-policy missing
        - --execution-environment-image ghcr.io/ansible/community-ansible-dev-tools:latest

  playbooks:
    create: ../default/create.yml
    prepare: ../default/prepare.yml
    destroy: ../default/destroy.yml
