---
ansible:
  playbooks:
    converge: converge.yml
    side_effect: side_effect.yml
    verify: verify.yml
scenario:
  name: upgrade
  test_sequence:
    - dependency
    - prepare
    - destroy
    - syntax
    - create
    - converge
    - verify
    - side_effect
    - verify
    - destroy
