---
ansible:
  playbooks:
    converge: converge.yml
    verify: verify.yml

scenario:
  name: talos
  test_sequence:
    - dependency
    - destroy
    - syntax
    - create
    - converge
    - idempotence
    - verify
    - side_effect
    - verify
    - destroy
