---
- name: Group installation hosts
  ansible.builtin.import_playbook: pokerops.baremetal.groups.talos

- name: Validate collection parameters
  ansible.builtin.import_playbook: pokerops.baremetal.validate

- name: Start media server
  ansible.builtin.import_playbook: pokerops.baremetal.media.start

- name: Fetch Talos volumes
  ansible.builtin.import_playbook: pokerops.baremetal.media.talos

- name: Boot from virtual media
  ansible.builtin.import_playbook: pokerops.baremetal.boot

- name: Discover the provisioning interfaces
  ansible.builtin.import_playbook: pokerops.baremetal.discover.talos

- name: Configure the machines
  ansible.builtin.import_playbook: pokerops.baremetal.seed.talos

- name: Bootstrap the cluster
  ansible.builtin.import_playbook: pokerops.baremetal.bootstrap.talos
  when: talos_bootstrap | default(True) | bool

- name: Stop media server
  ansible.builtin.import_playbook: pokerops.baremetal.media.stop
